# Generated by Django 6.0.4 on 2026-06-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
    ]
